name: Build and Release Ionic App

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # با push تگ‌های v1.0.0 و ... فعال می‌شود

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Ionic project
        run: npm run build --prod
      
      - name: Create archive
        run: |
          cd www
          zip -r ../app-build.zip .
          cd ..
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app-build.zip
          asset_name: app-build-${{ github.ref_name }}.zip
          asset_content_type: application/zip